### ISSUE TITLE
Bug quand on met cette map

### ISSUE THREAD

**Issue by Juiiceee** [toukoum/theCube#8]
NO textures/france.xpm
SO textures/france.xpm
WE textures/france.xpm
EA textures/france.xpm
F 220,100,0
C 225,30,0

		1111111111111111111111111
		1000000000110000000000001
		1011000001110000000000001
		1001000000000000000000001
111111111011000001110000000000001
100000000011000001110111111111111
11110111111111011100000010001
11110111111111011101010010001
11000000110101011100000010001
10000000000000001100000010001
10000000000000001101010010001
11000001110101011111011110N0111
11110111 1110101 101111010001
11111111 1111111 111111111111

**Comment by toukoum** [comment]
<img width="599" alt="image" src="https://github.com/toukoum/theCube/assets/69766890/b7cc76d7-bcc9-4a11-8b02-8f86ad39e4c6">

Oh my boys. thank's for the feedback i love you. the map is not surrounding with wall because i ignore tout les espace a l'interieur d'une map, donc rajoute des 1, a la place des space en bas de la map et ca devrait marcher

**Comment by Juiiceee** [comment]
Possible de le fix ? @KTrevis @toukoum

**Comment by KTrevis** [comment]
Bonjour,

Non.

**Comment by Juiiceee** [comment]
Je veux un fix Merci :)

**Comment by toukoum** [comment]
Bonjour, Votre grand-mère est elle boulangère ? Cordialement, René

**Comment by Juiiceee** [comment]
Bonjour monsieur Loukoum je comprends que vous soyez matrixe par tout ce qui touche de pres ou de loin a la patisserie / boulangerie car meme votre nom Monsieur Loukoum fait reference a une patiserie de l'Empire ottoman
Je vous souhaites une bonne journee de merde Cordialement
Monsieur Clitorine

**Comment by KTrevis** [comment]
Mon collègue se prénomme Toukoum, et non pas Loukoum, je trouve votre comportement déplacé monsieur Jus. Bonne journée.
